name: Auto Trigger Every 30 Minutes

on:
  schedule:
    - cron: "*/30 * * * *"   # every 30 minutes
  workflow_dispatch:         # allow manual runs

jobs:
  run-hello:
    runs-on: ubuntu-latest
    env:
      EXAMPLE_TOKEN: ${{ secrets.EXAMPLE_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Run script
        run: |
          python --version
          python helloworld.py
