name: Auto Trigger Every Minute

on:
  schedule:
    - cron: "* * * * *"   # Runs every minute

jobs:
  run-cron-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print timestamp
        run: echo "Triggered at $(date)"
